image: gitlab-registry.cern.ch/ci-tools/ci-worker:c8

variables:
  CMS_PATH: /cvmfs/cms.cern.ch/
  CMSSW_VERSION: CMSSW_12_0_0_pre4
  SCRAM_ARCH: cc8_amd64_gcc9
  BRANCH_UNDER_TEST: $CI_COMMIT_REF_NAME

workflow:
  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
    - if: '$CI_COMMIT_BRANCH == "master"'    
#    - if: '$CI_COMMIT_BRANCH == "ianCI"'    

stages:
  - setup_cmssw
  - build_cmssw
  - print_summary

setup_cmssw:
  stage: setup_cmssw
  tags:
    - docker
    - cvmfs
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo "CI variables $CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_BRANCH-$CI_PIPELINE_SOURCE"

#    - export CMS_PATH=/cvmfs/cms.cern.ch/
    - source $CMS_PATH/cmsset_default.sh
#    - export CMSSW_VERSION=CMSSW_12_0_0_pre4
#    - export SCRAM_ARCH=cc8_amd64_gcc9
#    - export BRANCH_UNDER_TEST=$CI_COMMIT_REF_NAME

    # Current branch automatically checked out via git clone (so  ECAL, Muon ...). Don't want this, so delete it. TO FIX: How stop it doing this?
    - pwd
    - ls -la
    - git branch -v
    - rm -rf *
    - scram project $CMSSW_VERSION
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git config --global user.name "Boris Johnson"
    - git config --global user.github Boris
    - git config --global user.email "Boris@John.son"
    - git cms-checkout-topic -u cms-L1TK:$BRANCH_UNDER_TEST
    - git branch -v
    - ls -la
  artifacts:
    expire_in: 1 day
    paths:
      - $CMSSW_VERSION   # Can't use env variable for this.

build_cmssw:
  stage: build_cmssw
  tags:
    - docker
    - cvmfs
  script:
#    - export CMS_PATH=/cvmfs/cms.cern.ch/
    - source $CMS_PATH/cmsset_default.sh
#    - export CMSSW_VERSION=CMSSW_12_0_0_pre4
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git branch -v
    - scram b -j8
  artifacts:
    expire_in: 1 day
    paths:
      - $CMSSW_VERSION

print_summary:
  stage: print_summary
  script:
    - env
