image: gitlab-registry.cern.ch/ci-tools/ci-worker:c8

stages:
  - setup_cmssw
  - build_cmssw

setup_cmssw:
  stage: setup_cmssw
  tags:
    - docker
    - cvmfs
  script:
    - export CMS_PATH=/cvmfs/cms.cern.ch/
    - source $CMS_PATH/cmsset_default.sh
    - export CMSSW_VERSION=CMSSW_12_0_0_pre4
    - export SCRAM_ARCH=cc8_amd64_gcc9
    # Seems ianCI automatically checked out (including ECAL, Muon ...)
    - ls -la
    - git branch -v
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo "CI variables $CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_BRANCH"
    - scram project $CMSSW_VERSION
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git config --global user.name "Boris Johnson"
    - git config --global user.github Boris
    - git config --global user.email "Boris@John.son"
    - git cms-checkout-topic -u cms-L1TK:L1TK-dev-12_0_0_pre4
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_12_0_0_pre4   # Can't use env variable for this.

build_cmssw:
  stage: build_cmssw
  tags:
    - docker
    - cvmfs
  script:
    - export CMS_PATH=/cvmfs/cms.cern.ch/
    - source $CMS_PATH/cmsset_default.sh
    - export CMSSW_VERSION=CMSSW_12_0_0_pre4
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git branch -v
    - scram b -j8
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_12_0_0_pre4
