image: gitlab-registry.cern.ch/ci-tools/ci-worker:c8

variables:
  CMS_PATH: /cvmfs/cms.cern.ch/
  CMSSW_VERSION: CMSSW_12_0_0_pre4
  SCRAM_ARCH: cc8_amd64_gcc9
  BRANCH_UNDER_TEST: $CI_COMMIT_REF_NAME

workflow:
  # Specify what triggers pipeline to run.
  rules:

# Check if user name matches gitlab token name  https://gitlab.cern.ch/tomalin/cmssw/-/settings/access_tokens 
# If so, mirror has just been updated by CI job running on github,
# rather than in response to user pushing code to github.
    - if: '$GITLAB_USER_NAME == "ian_CI_access"'

#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Default branch in github, e.g. L1TK-dev-12_0_0_pre4.
#    - if: '$CI_COMMIT_BRANCH == "ianCI"'    
#    - if: '$CI_COMMIT_BRANCH == "ianCItest"'   

stages:
  - setup_cmssw
  - build_cmssw
  - print_summary

setup_cmssw:
  stage: setup_cmssw
  tags:
    - docker
    - cvmfs
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo "CI variables $CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_BRANCH-$CI_PIPELINE_SOURCE"

    - source $CMS_PATH/cmsset_default.sh

    # Current branch automatically checked out via git clone (so  ECAL, Muon ...). Don't want this, so delete it. TO FIX: How stop it doing this?
    - pwd
    - ls -la
    - git branch -v
    - rm -rf *
    - scram project $CMSSW_VERSION
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git config --global user.name "Boris Johnson"
    - git config --global user.github Boris
    - git config --global user.email "Boris@uk.gov"
    - git cms-checkout-topic -u cms-L1TK:$BRANCH_UNDER_TEST
    - git branch -v
    - ls -la
  artifacts:
    expire_in: 1 day
    paths:
      - $CMSSW_VERSION 

build_cmssw:
  stage: build_cmssw
  tags:
    - docker
    - cvmfs
  script:
    - source $CMS_PATH/cmsset_default.sh
    - cd $CMSSW_VERSION/src/
    - eval `scram runtime -sh`
    - git branch -v
    - scram b -j8
  artifacts:
    expire_in: 1 day
    paths:
      - $CMSSW_VERSION

print_summary:
  stage: print_summary
  script:
    - echo "Detailed job output from CMSSW compilation & run"
    - echo "at $CI_PIPELINE_URL"
