image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

stages:
  - setup_cmssw
  - build_cmssw

setup_cmssw:
  stage: setup_cmssw
  tags:
    - docker
    - cvmfs
  script:
    - export TOPDIR=$PWD
    - export CMS_PATH=/cvmfs/cms.cern.ch/
    - source $CMS_PATH/cmsset_default.sh
    - export CMSSW_VERSION=CMSSW_11_3_0_pre3
    - export SCRAM_ARCH=slc7_amd64_gcc900
    - /cvmfs/cms.cern.ch/common/scram project  $CMSSW_VERSION
    - cd $CMSSW_VERSION/src/
    - eval `/cvmfs/cms.cern.ch/common/scram runtime -sh`
    - git config --global user.name "Boris Johnson"
    - git config --global user.github Boris
    - git config --global user.email "Boris@John.son"
    - git cms-checkout-topic -u cms-L1TK:L1TK-dev-11_3_0_pre3
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_11_3_0_pre3

build_cmssw:
  stage: build_cmssw
  tags:
    - docker
    - cvmfs
  script:
    - export TOPDIR=$PWD
    - export CMSSW_VERSION=CMSSW_11_3_0_pre3
    - export SCRAM_ARCH=slc7_amd64_gcc900
    - cd $CMSSW_VERSION/src/
    - eval `/cvmfs/cms.cern.ch/common/scram runtime -sh`
    - /cvmfs/cms.cern.ch/common/scram b -j8
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_11_3_0_pre3
