import FWCore.ParameterSet.Config as cms

def setupUseTMTT(process):
  process.TrackTriggerSetup.TrackingParticle.MinPt = 3.0
  process.TrackTriggerSetup.TMTT.WidthR   = 11
  process.TrackTriggerSetup.TMTT.WidthPhi = 14
  process.TrackTriggerSetup.TMTT.WidthZ   = 13
  process.TrackTriggerSetup.TrackFinding.MinPt        =  3.0
  process.TrackTriggerSetup.TrackFinding.MaxEta       =  2.4
  process.TrackTriggerSetup.TrackFinding.ChosenRofPhi = 67.24
  process.TrackTriggerSetup.TrackFinding.NumLayers    =  8
  process.TrackTriggerSetup.HoughTransform.MinLayers = 5
  process.TrackTriggerSetup.CleanTrackBuilder.MaxStubs = 4
  process.TrackTriggerSetup.KalmanFilter.RangeFactor     =  3.0
  process.TrackTriggerSetup.KalmanFilter.NumWorker       =  4
  process.TrackTriggerSetup.KalmanFilter.MaxLayers       =  8
  process.TrackTriggerSetup.KalmanFilter.MaxGaps         =  2
  process.TrackTriggerSetup.KalmanFilter.ShiftInitialC00 = 0
  process.TrackTriggerSetup.KalmanFilter.ShiftInitialC11 = 0
  process.TrackTriggerSetup.KalmanFilter.ShiftInitialC22 = 0
  process.TrackTriggerSetup.KalmanFilter.ShiftInitialC33 = 0
  process.TrackTriggerSetup.KalmanFilter.BaseShift       = 0
  process.TrackTriggerSetup.KalmanFilter.ShiftChi20      = 0
  process.TrackTriggerSetup.KalmanFilter.ShiftChi21      = 0
  process.TrackTriggerSetup.KalmanFilter.PowCutChi2      = 1
  process.TrackTriggerKalmanFilterFormats.BaseShiftx0           = (  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftx1           = ( -10, -10, -10, -10, -10, -10, -10, -10 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftx2           = (  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftx3           = (  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftr0           = (  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftr1           = (  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3 )

  process.TrackTriggerKalmanFilterFormats.BaseShiftS00          = (   0,   0,   0,   1,   2,   3,   3,   1 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftS01          = (  -6,  -6,  -5,  -4,  -4,  -4,  -5,  -6 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftS12          = (   6,   6,   5,   6,   7,   9,   9,   7 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftS13          = (   5,   5,   5,   6,   6,   6,   6,   4 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftK00          = (  -8,  -8,  -7,  -8,  -8,  -9, -10, -11 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftK10          = ( -13, -13, -12, -13, -14, -15, -16, -17 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftK21          = ( -13, -13, -12, -13, -13, -14, -14, -15 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftK31          = ( -13, -13, -12, -14, -14, -15, -16, -17 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftR00          = (  -7,  -7,  -7,  -6,  -5,  -3,  -3,  -4 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftR11          = (   4,   4,   3,   4,   6,   9,   9,   7 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR00Approx = ( -16, -16, -17, -16, -15, -17, -17, -18 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR11Approx = ( -26, -26, -26, -27, -27, -30, -34, -34 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR00Cor    = ( -15, -15, -15, -15, -15, -15, -15, -15 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR11Cor    = ( -15, -15, -15, -15, -15, -15, -15, -15 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR00       = ( -16, -16, -26, -25, -25, -26, -27, -27 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftInvR11       = ( -26, -26, -35, -36, -37, -38, -43, -43 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC00          = (   7,   8,   6,   5,   9,   9,   6,   4 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC01          = (   1,   3,   0,  -1,   2,   1,  -2,  -3 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC11          = (  -4,  -2,  -5,  -6,  -5,  -6,  -8,  -9 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC22          = (   8,   8,   6,   7,  10,  10,   7,   5 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC23          = (   7,   8,   5,   4,   6,   7,   5,   4 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftC33          = (   7,   7,   4,   3,   5,   5,   4,   3 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftr02          = (  -7,  -7,  -4,  -3,  -3,  -3,  -2,  -2 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftr12          = (   1,   1,   7,   8,   9,  10,   9,   9 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftchi20        = ( -13, -13, -13, -12, -11, -11, -10, -10 )
  process.TrackTriggerKalmanFilterFormats.BaseShiftchi21        = ( -14, -14, -13, -12, -11, -11, -10, -10 )
  return process
