name: Mirror and run GitLab CI

on: # Controls when the action will run.
  workflow_dispatch:
  push: # Please add your branch down here if you want CI to run for each push to it.
    branches: [ianCI]
  pull_request: # Run CI if someone makes a PR to default branch.
    branches: [L1TK-dev-12_0_0_pre4]
    
env:
  current_branch: 'master' # fallback branch

jobs:
  mirror_trig: # https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci
    name: mirror_trig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Debug
      run: |
        echo "github.ref = ${{ github.ref }}"
    - name: Redefine branch on pull_request
      if: github.event_name == 'pull_request'
      run: |
        echo "IAN_PULL_START $current_branch AND $GITHUB_ENV"
        echo "current_branch=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV
        echo "IAN_PULL_DONE $current_branch AND $GITHUB_ENV"
    - name: Redefine branch on push
      if: github.event_name == 'push'
      run: |
        echo "IAN_PUSH_START $current_branch AND $GITHUB_ENV"
        echo "current_branch=$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
        echo "IAN_PUSH_DONE $current_branch AND $GITHUB_ENV"
    - name: Mirror + trigger CI
      # Forked from https://github.com/SvanBoxel/gitlab-mirror-and-ci-action .
      #uses: aperloff/gitlab-mirror-and-ci-action@master
      uses: cms-L1TK/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.cern.ch/tomalin/cmssw" # mirror repo
      env:
        GITLAB_HOSTNAME: "gitlab.cern.ch"
        GITLAB_USERNAME: "tomalin"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Generate token here: https://gitlab.cern.ch/tomalin/cmssw/-/settings/access_tokens and add it to GitHub secrets https://github.com/cms-L1TK/cmssw/settings/secrets/actions   
        GITLAB_PROJECT_ID: "124554" # ID visible at https://gitlab.cern.ch/tomalin/cmssw 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret
        CHECKOUT_BRANCH: ${{ env.current_branch }} # New non-GITHUB variable to make push and PR work
        REMOVE_BRANCH: "true" # Forces refresh of branch on mirror, by deleting it.
        REBASE_MASTER: "false" # If true would rebase to "master", which isn't used in cms-L1TK.
    - name: print summary
      run: |
        echo 'See link "Pipeline URL" in section "Mirror + trigger CI" above for details of CMSSW compilation & run'
